baseURL      = 'https://georgi-trevnenski.dev/'
languageCode = 'en-us'
title        = 'Georgi Trevnenski'
canonifyURLs = true


[params]
  description = "Georgi Trevnenski personal website"
  keywords    = "Georgi Trevnenski, personal website, portfolio"
  favicon     = "img/favicon.png"

  [params.author]
    name = 'Georgi Trevnenski'
    avatar = 'img/profile_pic.png'


# Add theme using Hugo modules
[module]
  [[module.imports]]
    path = "github.com/hugo-porto/theme"

# Enable unsafe HTML in markdown for inline scripts and styles
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
